// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvvsefzarzfisxrpfygw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2dnNlZnphcnpmaXN4cnBmeWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3Mjc0NTksImV4cCI6MjA2NzMwMzQ1OX0.1iRhznIuX7F7cMaxTMWTeJrbVZrEjFQmmAO2HrynEBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});